-- Active: 1737131686225@@127.0.0.1@5432@DesarrolloWeb
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(50),
    cellphone VARCHAR(9) NOT NULL,
    dni VARCHAR(8) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

DROP TABLE IF EXISTS RACE

CREATE TABLE RACE (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

DROP TABLE IF EXISTS DOG;

CREATE TABLE DOG (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    age VARCHAR(2) NOT NULL,
    raceId INT,
    CONSTRAINT fkIdRace FOREIGN KEY (raceId) REFERENCES RACE(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)